// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH1IrwUP_OuuZ_1dlgcGnpCuYWH_sCh5c',
    appId: '1:789698753010:web:d7c94593acbecc6274fb6b',
    messagingSenderId: '789698753010',
    projectId: 'shreya-shraddha-project',
    authDomain: 'shreya-shraddha-project.firebaseapp.com',
    storageBucket: 'shreya-shraddha-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4669OFjKdzZ5atTnZ_uWTvDCPf1hDK2w',
    appId: '1:789698753010:android:ae10ddccd9c10ea774fb6b',
    messagingSenderId: '789698753010',
    projectId: 'shreya-shraddha-project',
    storageBucket: 'shreya-shraddha-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl91l50cmEeUdjc3V9wESbuVSGW3BzRKs',
    appId: '1:789698753010:ios:a769472d15fed62b74fb6b',
    messagingSenderId: '789698753010',
    projectId: 'shreya-shraddha-project',
    storageBucket: 'shreya-shraddha-project.appspot.com',
    iosBundleId: 'com.example.ss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBl91l50cmEeUdjc3V9wESbuVSGW3BzRKs',
    appId: '1:789698753010:ios:a95226c6d637088174fb6b',
    messagingSenderId: '789698753010',
    projectId: 'shreya-shraddha-project',
    storageBucket: 'shreya-shraddha-project.appspot.com',
    iosBundleId: 'com.example.ss.RunnerTests',
  );
}
